### ISSUE TITLE
KeyError: 'resume_settings'

### ISSUE THREAD

**Issue by arbrog** [aka-katto/dandere2x#110]
Version 1.8
Linux (Ubuntu 18 LTS)

Error when upscaling video through GUI
```is not suspend file
output_file = /home/ai/Documents/dandere/long_ren_[vulkan][s2][n3][b20][q85].mp4
input_file = /home/ai/Documents/dandere/long_ren.mp4
block_size = 20
block_size = 20
image_quality = 85
waifu2x_type = vulkan
workspace = ../workspace/default/
log file is: /home/ai/Documents/dandere/dandere2x-1.8/src/workspace/log_folder/dandere2x1583267196.5499072.log
Traceback (most recent call last):
  File "gui_driver.py", line 227, in press_upscale_button
    self.thread = QtDandere2xThread(self, config_yaml)
  File "gui_driver.py", line 23, in __init__
    self.dandere2x = Dandere2x(context)
  File "/home/ai/Documents/dandere/dandere2x-1.8/src/dandere2x.py", line 71, in __init__
    if self.context.config_yaml['resume_settings']['resume_session']:
KeyError: 'resume_settings'
Aborted (core dumped)
```
Fixed by copying the following from windows YAML into Linux one
```# don't touch these unless you know what you're doing!
resume_settings:
  resume_session: false
  signal_merged_count: 0
  nosound_file: null
```

**Comment by aka-katto** [comment]
Pushed to origin. Thanks for reminding me this was an issue.

Does everything else work?

**Comment by arbrog** [comment]
np
once I fixed that I ran into an issue because snap installing waifu2x-ncnn-vulkan `sudo snap install waifu2x-ncnn-vulkan --edge` doesn't put it where waifu2x expects (think snap packages are stored in `/snap/` but im not super familiar with the inner workings of Linux packages so I may be mistaken)
```
Exception in thread dandere2x_thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ai/Documents/dandere/dandere2x-1.8/src/dandere2x.py", line 253, in run
    self.__upscale_first_frame()
  File "/home/ai/Documents/dandere/dandere2x-1.8/src/dandere2x.py", line 110, in __upscale_first_frame
    output_file=self.context.merged_dir + "merged_" + str(self.first_frame) + self.context.extension_type)
  File "/home/ai/Documents/dandere/dandere2x-1.8/src/wrappers/waifu2x/waifu2x_vulkan.py", line 161, in upscale_file
    stdout=console_output)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/waifu2x-ncnn-vulkan': '/usr/bin/waifu2x-ncnn-vulkan'
```

**Comment by arbrog** [comment]
tried making the snap waifu2x binary a hard link to /usr/bin which got me further but 
log:
```
INFO:dandere2xlib.utils.dandere2x_utils:/home/ai/Documents/dandere/dandere2x-1.8/src/workspace/default/nosound.mp4 does not exist, waiting
INFO:wrappers.ffmpeg.progressive_frame_extractor_ffmpeg:extracting frames
INFO:root:Could not upscale first file.. check logs file to see what's wrong
INFO:root:Exiting Dandere2x...
```

looked in the workspace /default/console_output/vulkan_upscale_frame.txt
```
realpath: invalid option -- 'i'
Try 'realpath --help' for more information.
['/usr/bin/waifu2x-ncnn-vulkan', '-i', '/home/ai/Documents/dandere/dandere2x-1.8/src/workspace/default/inputs/frame1.jpg', '-n', '3', '-s', '2', '-t', '256', '-o', '/home/ai/Documents/dandere/dandere2x-1.8/src/workspace/default/merged/merged_1.jpg']
```
is this because the snap waifu2x package is super old?

**Comment by aka-katto** [comment]
> fault/console

Oh set it to waifu2x-ncnn-vulkan-legacy, it's for the snap package.

The snap package didnt work for me recently, though. Let me know if it works for you.

**Comment by arbrog** [comment]
actually did seem to work for me. was just kinda slow despite having significantly more CPU and GPU resources than my windows machine (which I ran the same clip-on)
